package org.sakaiproject.myo.entity;

import java.math.BigInteger;
import java.util.Date;


public class myprofile_user {
	private BigInteger ID;
	private int VERSION;
	private String PERSON_TYPE;
	private String UUID;
	private String LAST_MODIFIED_BY;
	private String LAST_MODIFIED_DATE;
	private String CREATED_BY;
	private String CREATED_DATE;
	private String AGENT_UUID;
	private String TYPE_UUID;
	private String COMMON_NAME;
	private String DESCRIPTION;
	private String SEE_ALSO;
	private String STREET;
	private String SURNAME;
	private String TELEPHONE_NUMBER;
	private String FAX_NUMBER;
	private String LOCALITY_NAME;
	private String OU;
	private String PHYSICAL_DELIVERY_OFFICE_NAME;
	private String POSTAL_ADDRESS;
	private String POSTAL_CODE;
	private String POST_OFFICE_BOX;
	private String STATE_PROVINCE_NAME;
	private String STREET_ADDRESS;
	private String TITLE;
	private String BUSINESS_CATEGORY;
	private String CAR_LICENSE;
	private String DEPARTMENT_NUMBER;
	private String DISPLAY_NAME;
	private String EMPLOYEE_NUMBER;
	private String EMPLOYEE_TYPE;
	private String GIVEN_NAME;
	private String HOME_PHONE;
	private String HOME_POSTAL_ADDRESS;
	private String INITIALS;
	private String JPEG_PHOTO;
	private String LABELED_URI;
	private String MAIL;
	private String MANAGER;
	private String MOBILE;
	private String ORGANIZATION;
	private String PAGER;
	private String PREFERRED_LANGUAGE;
	private String ROOM_NUMBER;
	private String SECRETARY;
	private String UID_C;
	private String USER_CERTIFICATE;
	private String USER_PKCS12;
	private String USER_SMIME_CERTIFICATE;
	private String X500_UNIQUE_ID;
	private String AFFILIATION;
	private String ENTITLEMENT;
	private String NICKNAME;
	private String ORG_DN;
	private String ORG_UNIT_DN;
	private String PRIMARY_AFFILIATION;
	private String PRIMARY_ORG_UNIT_DN;
	private String PRINCIPAL_NAME;
	private String PRINCIPAL_NAME_PRIOR;
	private String SCOPED_AFFILIATION;
	private String TARGETED_ID;
	private String ASSURANCE;
	private String UNIQUE_ID;
	private String ORCID;
	private String CAMPUS;
	private String HIDE_PRIVATE_INFO;
	private String HIDE_PUBLIC_INFO;
	private String NOTES;
	private String PICTURE_URL;
	private String SYSTEM_PICTURE_PREFERRED;
	private String ferpaEnabled;
	private Date dateOfBirth;
	private String locked;
	private String FAVOURITE_BOOKS;
	private String FAVOURITE_TV_SHOWS;
	private String FAVOURITE_MOVIES;
	private String FAVOURITE_QUOTES;
	private String EDUCATION_COURSE;
	private String EDUCATION_SUBJECTS;
	private String NORMALIZEDMOBILE;
	private String STAFF_PROFILE;
	private String UNIVERSITY_PROFILE_URL;
	private String ACADEMIC_PROFILE_URL;
	private String PUBLICATIONS;
	private String BUSINESS_BIOGRAPHY;
	private String PHONETIC_PRONUNCIATION;
	private String PRONOUNS;
}

